version: '3.1'

services:

  dokuwiki:
    image: dokuwiki
    environment:
        - TITLE=Test title
        - ADMIN_USERNAME=admin
        - ADMIN_FULLNAME=test admin
        - ADMIN_EMAIL=test.admin@test.com
        - ADMIN_PASSWORD=password

        - ACL_POLICY=closed
        - ALLOW_REG=FALSE
        - LICENSE=gnufdl
        - SEND_USAGE_DATA=TRUE
        - APP_LANGUAGE=en

        - USE_LDAP=TRUE
        - LDAP_BASE_DN=dc=example,dc=com
        - LDAP_HOST=fd
        - LDAP_ADMIN_PASS=password
        - LDAP_ADMIN_GROUP=admin
    ports:
      - 8080:80
    volumes:
      - /tmp/dokuwiki:/var/www/dokuwiki/
    networks:
      default:
    deploy:
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
      mode: global

  fd:
    image: dotriver/fusiondirectory
    ports:
      - "8081:80"
    environment:
      DOMAIN: example.com
      ADMIN_PASS: password
      CONFIG_PASS: password
    volumes:
      - openldap-data:/var/lib/openldap/
      - openldap-config:/etc/openldap/

volumes:
    mariadb-data:
    mariadb-config:
    openldap-config:
    openldap-data: